/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as NoAuthRouteImport } from './routes/_noAuth'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as NoAuthSignUpRouteImport } from './routes/_noAuth/sign-up'
import { Route as NoAuthSignInRouteImport } from './routes/_noAuth/sign-in'
import { Route as AuthenticatedConcertsIndexRouteImport } from './routes/_authenticated/concerts/index'

const NoAuthRoute = NoAuthRouteImport.update({
  id: '/_noAuth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const NoAuthSignUpRoute = NoAuthSignUpRouteImport.update({
  id: '/sign-up',
  path: '/sign-up',
  getParentRoute: () => NoAuthRoute,
} as any)
const NoAuthSignInRoute = NoAuthSignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => NoAuthRoute,
} as any)
const AuthenticatedConcertsIndexRoute =
  AuthenticatedConcertsIndexRouteImport.update({
    id: '/concerts/',
    path: '/concerts/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/sign-in': typeof NoAuthSignInRoute
  '/sign-up': typeof NoAuthSignUpRoute
  '/concerts': typeof AuthenticatedConcertsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/sign-in': typeof NoAuthSignInRoute
  '/sign-up': typeof NoAuthSignUpRoute
  '/concerts': typeof AuthenticatedConcertsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/_noAuth': typeof NoAuthRouteWithChildren
  '/_noAuth/sign-in': typeof NoAuthSignInRoute
  '/_noAuth/sign-up': typeof NoAuthSignUpRoute
  '/_authenticated/concerts/': typeof AuthenticatedConcertsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/sign-in' | '/sign-up' | '/concerts'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/sign-in' | '/sign-up' | '/concerts'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/_noAuth'
    | '/_noAuth/sign-in'
    | '/_noAuth/sign-up'
    | '/_authenticated/concerts/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  NoAuthRoute: typeof NoAuthRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_noAuth': {
      id: '/_noAuth'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof NoAuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_noAuth/sign-up': {
      id: '/_noAuth/sign-up'
      path: '/sign-up'
      fullPath: '/sign-up'
      preLoaderRoute: typeof NoAuthSignUpRouteImport
      parentRoute: typeof NoAuthRoute
    }
    '/_noAuth/sign-in': {
      id: '/_noAuth/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof NoAuthSignInRouteImport
      parentRoute: typeof NoAuthRoute
    }
    '/_authenticated/concerts/': {
      id: '/_authenticated/concerts/'
      path: '/concerts'
      fullPath: '/concerts'
      preLoaderRoute: typeof AuthenticatedConcertsIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedConcertsIndexRoute: typeof AuthenticatedConcertsIndexRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedConcertsIndexRoute: AuthenticatedConcertsIndexRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

interface NoAuthRouteChildren {
  NoAuthSignInRoute: typeof NoAuthSignInRoute
  NoAuthSignUpRoute: typeof NoAuthSignUpRoute
}

const NoAuthRouteChildren: NoAuthRouteChildren = {
  NoAuthSignInRoute: NoAuthSignInRoute,
  NoAuthSignUpRoute: NoAuthSignUpRoute,
}

const NoAuthRouteWithChildren =
  NoAuthRoute._addFileChildren(NoAuthRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  NoAuthRoute: NoAuthRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
