services:
  db:
    image: neondatabase/neon_local:latest
    ports:
      - "5432:5432"
    environment:
      NEON_API_KEY: ${NEON_API_KEY}
      NEON_PROJECT_ID: ${NEON_PROJECT_ID}
      BRANCH_ID: br-blue-snow-agz9dub6
      DRIVER: serverless
      DELETE_BRANCH: false
